name: Terraform Azure AKS Infrastructure

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform Environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

      action:
        description: 'Terraform Action'
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.9.8"
  TF_ARTIFACT: terraform-plan
  TF_IN_AUTOMATION: true
  TF_INPUT: false

concurrency:
  group: terraform-${{ github.event.inputs.environment || 'dev' }}
  cancel-in-progress: false

jobs:

  terraform-scan:
    name: Terraform Security & Quality Scan
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: environments/${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: latest

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip3 install checkov

      - name: Install tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.TF_WORKING_DIR }}
          soft_fail: true

      - name: Terraform Version
        run: terraform version

      - name: TFLint Version
        run: tflint --version

      - name: Checkov Version
        run: checkov --version

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -recursive

      - name: TFLint
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tflint --init
          tflint

      - name: Checkov Security Scan
        run: |
          checkov \
            -d "${TF_WORKING_DIR}" \
            --framework terraform

  terraform-plan:
    name: Terraform Validate & Plan
    needs: terraform-scan
    runs-on: ubuntu-latest

    if: >
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.action == 'plan' ||
      github.event.inputs.action == 'apply'

    env:
      TF_WORKING_DIR: environments/${{ github.event.inputs.environment || 'dev' }}

      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login - OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-statebk" \
            -backend-config="storage_account_name=ashustgstatebk" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=${{ github.event.inputs.environment || 'dev' }}.tfstate" \
            -backend-config="use_oidc=true"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TF_ARTIFACT }}
          path: ${{ env.TF_WORKING_DIR }}/tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest

    if: >
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.action == 'apply' &&
      github.ref == 'refs/heads/main'

    environment:
      name: terraform-${{ github.event.inputs.environment }}

    env:
      TF_WORKING_DIR: environments/${{ github.event.inputs.environment }}

      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login - OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TF_ARTIFACT }}
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-statebk" \
            -backend-config="storage_account_name=ashustgstatebk" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=${{ github.event.inputs.environment }}.tfstate" \
            -backend-config="use_oidc=true"

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
        run: terraform apply -auto-approve tfplan

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    if: >
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.action == 'destroy' &&
      github.ref == 'refs/heads/main'

    environment:
      name: terraform-${{ github.event.inputs.environment }}

    env:
      TF_WORKING_DIR: environments/${{ github.event.inputs.environment }}

      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login - OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-statebk" \
            -backend-config="storage_account_name=ashustgstatebk" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=${{ github.event.inputs.environment }}.tfstate" \
            -backend-config="use_oidc=true"

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
        run: terraform destroy -auto-approve
